### ISSUE TITLE
移动到可视区域外的数据不显示

### ISSUE THREAD

**Issue by just-ads** [deyihu/maptalks.tileclusterlayer#2]
在dom中放大到合适的层级，再移动去应该有数据的地方，实际上没marker加载出来，
应该是聚合的时候有currentTileCache就直接return了，应该是continue；
![image](https://user-images.githubusercontent.com/50706050/135373980-c3b6928b-392a-4f85-aed1-8a9d7df141bd.png)

**Comment by deyihu** [comment]
@PZD2937  3q
this fix by https://github.com/deyihu/maptalks.tileclusterlayer/commit/da7d73b44a08a4d988af6e9ccd1f1e5afae1d09f
you can upgrade 0.0.4
